create table public.discussion_forum (
  id bigint generated by default as identity not null,
  parent_id bigint null,
  parent_type text null, -- 'LOG' or 'FEATURE'
  user_id uuid not null,
  comment_text text not null,
  created_at timestamp with time zone null default now(),
  attachment_url text null,
  constraint discussion_forum_pkey primary key (id),
  constraint discussion_forum_user_id_fkey foreign KEY (user_id) references profiles (id) on delete CASCADE
) TABLESPACE pg_default;

-- Aktifkan RLS
ALTER TABLE public.discussion_forum ENABLE ROW LEVEL SECURITY;

-- Policy untuk melihat komentar (Semua user yang login)
DROP POLICY IF EXISTS "Anyone can view comments" ON public.discussion_forum;
CREATE POLICY "Anyone can view comments" 
ON public.discussion_forum FOR SELECT 
TO authenticated 
USING (true);

-- Policy untuk mengirim komentar (Hanya jika user_id sesuai dengan yang sedang login)
DROP POLICY IF EXISTS "Users can insert their own comments" ON public.discussion_forum;
CREATE POLICY "Users can insert their own comments" 
ON public.discussion_forum FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = user_id);

-- Policy untuk menghapus komentar sendiri
DROP POLICY IF EXISTS "Users can delete their own comments" ON public.discussion_forum;
CREATE POLICY "Users can delete their own comments" 
ON public.discussion_forum FOR DELETE 
TO authenticated 
USING (auth.uid() = user_id);

-- Index untuk performa
CREATE INDEX IF NOT EXISTS idx_discussion_parent ON public.discussion_forum USING btree (parent_id, parent_type);
